uploads = []
generated = []

[[outputs]]
id = "yRFsYwrOzNtuqS7IaBN6k"
uri = "file://www.tar.gz"
type = "unspecified"
title = "www folder (Capacitor APK)"

[[outputs]]
id = "IECbkgWNk1NB2lKVcqpKp"
uri = "file://www.zip"
type = "unspecified"
title = "www.zip — offline music fix (no SW in APK)"
