[[pages]]
path = "/"
screenshotTimestamp = "2026-05-09T01:26:03Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/652035eb-0e0f-46cb-92a2-50f2ef87c880/e55adc62-d56b-405c-aebd-7e81bb71cb6d/1G7D0EC"

[[pages]]
path = "/game/index.html"
screenshotTimestamp = "2026-05-09T02:39:42Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/652035eb-0e0f-46cb-92a2-50f2ef87c880/e55adc62-d56b-405c-aebd-7e81bb71cb6d/5wbmfOv"
